[package]
name = "dice_roller"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }

[dev-dependencies]
criterion = "0"

[[bench]]
name = "benchmark"
harness = false
